#!/usr/bin/env php
<?php
use Slim\{App, Container};
use Slion\{Run};
use Tracy\Debugger;

/**
 * @author andares
 */
define('IN_CONSOLE', 1);

// 载入环境
$settings = require __DIR__ . '/src/settings.php';
require __DIR__ . '/vendor/autoload.php';

/* @var $run \Slion\Run */
$run->add('chord', __DIR__)

    ->setup(70, function(string $root) {
        $app        = $this->app();
        $container  = $this->container();
        $settings   = $this->settings();

        // 加入容器
        $container['chord'] = function ($c) {
            return new Slion\Chord($c);
        };
        $chord = $container->get('chord');
        /* @var $chord \Slion\Console */

        // 载入slion自带功能
        $chord->map($this->root('slion') . "/classes/Slion", 'Slion');
        $chord->setDefaultDomain('slion');
    }, 'chord init');

// 获取 $chord
$chord = $run()->getContainer()->get('chord');
/* @var $chord \Slion\Console */

// 载入commands
$commands = __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'commands.php';
file_exists($commands) && require $commands;

// 扫描目录
$classes_dir = __DIR__ . "/src/classes";
if (file_exists($classes_dir)) {
    $it = new \RecursiveDirectoryIterator($classes_dir);
    foreach ($it as $file) {
        /* @var $file \SplFileInfo */
        if (!$file->isDir()) {
            continue;
        }
        $chord->map($file->getRealPath(), $file->getBasename());
    }
}

try {
    $result = $chord($argv);
    $chord->ec("$result");
} catch (Throwable $exc) {
    $chord->ec($exc->getMessage(), 'halt');

    $chord->ec($exc->getTraceAsString());
}
//du($chord);
