<?php

namespace Slion;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-02 at 01:49:46.
 */
class AbortTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Abort
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
//        $this->object = new Abort;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Slion\Abort::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        try {
            throw abort(new \Exception('hello'))
                ->set('show', 0)
                ->set('backend', true);
        } catch (Abort $abort) {
            du($abort->getMessage());   // 获取Exception的message
            du($abort->all());          // 获取额外信息
            du($abort()->getFile());    // 直接访问原始Exception
            du("$abort");
        }

        $backend = new class {
            public function __invoke(Abort $abort, $level = 1) {
                $abort->show    = 0;
                $abort->backend = true;
                $abort->level   = $level;

                $this->log($abort);
                $this->sendMail($abort);
                return $abort;
            }

            private function log(Abort $abort) {
                error_log($abort()->getTraceAsString());
            }

            private function sendMail(Abort $abort) {
                // send mail...
            }
        };

        try {
            $user_id = 1;
            // ...
            throw abort(new \Exception('hello'), $backend, 3)->set('from_id', $user_id);
        } catch (Abort $abort) {
            du($abort->getMessage());
            du($abort->all());
            du($abort()->getFile());
            du("$abort");
        }
    }

    /**
     * @covers Slion\Abort::__set
     * @todo   Implement test__set().
     */
    public function test__set() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Abort::__get
     * @todo   Implement test__get().
     */
    public function test__get() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Abort::__isset
     * @todo   Implement test__isset().
     */
    public function test__isset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Abort::__unset
     * @todo   Implement test__unset().
     */
    public function test__unset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Abort::push
     * @todo   Implement testPush().
     */
    public function testPush() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Abort::pop
     * @todo   Implement testPop().
     */
    public function testPop() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Abort::set
     * @todo   Implement testSet().
     */
    public function testSet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Abort::fill
     * @todo   Implement testFill().
     */
    public function testFill() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Abort::get
     * @todo   Implement testGet().
     */
    public function testGet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Abort::it
     * @todo   Implement testIt().
     */
    public function testIt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Abort::keys
     * @todo   Implement testKeys().
     */
    public function testKeys() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Abort::has
     * @todo   Implement testHas().
     */
    public function testHas() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Abort::remove
     * @todo   Implement testRemove().
     */
    public function testRemove() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Abort::clear
     * @todo   Implement testClear().
     */
    public function testClear() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Abort::count
     * @todo   Implement testCount().
     */
    public function testCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
