<?php

namespace Slion;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-10 at 18:11:21.
 */
class PackTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Pack
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Pack;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Slion\Pack::encode
     * @todo   Implement testEncode().
     */
    public function testEncode() {
        $a = Pack::encode('json', ['a' => 1,2,3]);
    }

    /**
     * @covers Slion\Pack::decode
     * @todo   Implement testDecode().
     */
    public function testDecode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Pack::getCodec
     * @todo   Implement testGetCodec().
     */
    public function testGetCodec() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Pack::setCodec
     * @todo   Implement testSetCodec().
     */
    public function testSetCodec() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
