<?php

namespace Slion\Utils;
use Slion\Test;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-19 at 00:58:50.
 */
class IdGeneratorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var IdGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IdGenerator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Slion\Utils\IdGenerator::prepare
     * @todo   Implement testPrepare().
     */
    public function testPrepare() {
        du(hash_algos());

        $result = Test::run(function() {
            return $this->object->prepare('ddddd')->hash_hmac(microtime(), true)
                ->base64()->get();
        });
        du($result);

        $result = Test::run(function() {
            $this->object->algo = 'fnv164';
            return $this->object->prepare(microtime())->hash_hmac('acbde')
                ->gmp_strval()->get();
        }, 1);
        du($result);

        $result = Test::run(function() {
            return $this->object->prepare('ddddd')->hash_hmac(microtime())
                ->pack('H*')->base64()->get();
        });

        $result = Test::run(function() {
            return $this->object->prepare('ddddd')->hash_hmac(microtime())
                ->base_convert(16, 36)->strtoupper()->get();
        });

        $result = Test::run(function() {
            return $this->object->prepare('ddddd')->hash_hmac(microtime())
                ->gmp_strval()->get();
        });
        du($result);
    }

    /**
     * @covers Slion\Utils\IdGenerator::get
     * @todo   Implement testGet().
     */
    public function testGet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Utils\IdGenerator::hash_hmac
     * @todo   Implement testHash_hmac().
     */
    public function testHash_hmac() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Utils\IdGenerator::base64
     * @todo   Implement testBase64().
     */
    public function testBase64() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Utils\IdGenerator::urlencode
     * @todo   Implement testUrlencode().
     */
    public function testUrlencode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Utils\IdGenerator::pack
     * @todo   Implement testPack().
     */
    public function testPack() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Utils\IdGenerator::strtoupper
     * @todo   Implement testStrtoupper().
     */
    public function testStrtoupper() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Utils\IdGenerator::strtolower
     * @todo   Implement testStrtolower().
     */
    public function testStrtolower() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Utils\IdGenerator::base_convert
     * @todo   Implement testBase_convert().
     */
    public function testBase_convert() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
