<?php

namespace Slion\Utils;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-10 at 03:03:13.
 */
class LoggerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Logger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        global $app;
        /* @var $app \Slim\App */
        $this->object = $app->getContainer()->get('logger');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Slion\Utils\Logger::__invoke
     * @todo   Implement test__invoke().
     */
    public function test__invoke() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Slion\Utils\Logger::__call
     * @todo   Implement test__call().
     */
    public function test__call() {
        $log_file = "{$this->object->directory}/custom.log";
//        unlink($log_file);
        $this->object->custom('unit test');
        $this->assertTrue(file_exists($log_file));
    }

}
